name: daily-devcard
on:
  workflow_dispatch:  # Manual trigger
  push:  # Triggers on push to the main branch
    branches:
      - main
  schedule:  # Scheduled run
    - cron: "0 0 * * *"  # Runs every night at midnight

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.USER_ID }}  # Use the secret here
          commit_message: "chore: update devcard"
